### ISSUE TITLE
Take over c14bazAAR's material thesaurus

### ISSUE THREAD

**Issue by joeroe** [joeroe/cleanc14#2]
[c14bazAAR](https://github.com/ropensci/c14bazAAR) v. 3.0.0 deprecated `classify_material()`. @nevrome, @dirkseidensticker: if you have no objections, I would like to copy the material thesaurus (https://github.com/ropensci/c14bazAAR/blob/master/data-raw/material_thesaurus.csv) over to this repository to keep it going.

Recently I've been using `controller::control(x$material, thesaurus = c14bazAAR::material_thesaurus)` (with [controller](https://github.com/joeroe/controller)) to replicate its functionality outside of the context of a `c14bazAAR::c14_date_list` object anyway, so there wouldn't even be a need to write a new function.

**Comment by nevrome** [comment]
I say: Sure go ahead! I'm happy that you want to adopt it, because a lot of work went into it. I may even contribute again in the future.

Just give proper attribution. I especially want to highlight the contributions of @yesdavid (and of course @dirkseidensticker, as always). David did not end up on the c14bazAAR paper, but also invested a lot of time in updating and cleaning the material thesaurus back then in Kiel. He's also the one who initially started the relevant [changelog](https://github.com/ropensci/c14bazAAR/blob/master/data-raw/material_thesaurus_comments.md), if I remember correctly.

**Comment by joeroe** [comment]
Great! I had a quick look into copying files between repositories with their histories, and it seems to be possible, if a little hacky. I will try it out maybe. Otherwise, I'm very happy to add all the contributors to the file(s) to the R package authors.

**Comment by dirkseidensticker** [comment]
I have no issue, but it is possible to re-licence GPL to MIT? I think we would need to create a new version under MIT specifically?

**Comment by nevrome** [comment]
It would indeed be interesting, if you could copy individual files with their history to another repo. But don't wreck your repo for that - a sentence in the README and a contributing role in the R DESCRIPTION file is enough for me.

I don't know about the technicalities Dirk brought up, but for me personally it's ok to make these two files more easily available under an MIT license.

**Comment by joeroe** [comment]
"Re-license" is probably not the right word: what we're doing is distributing the same code under a new license (MIT). The old license (GPL) would still apply, separately, to previous versions released with that license. My understanding is that this is fine as long as all the copyright holders consent, for which this issue would serve as a record.

**Comment by dirkseidensticker** [comment]
So, in order to make it formal: I consent to distribute the thesauri under the MIT licence

**Comment by zoometh** [comment]
This is fine fo me, thanks

**Comment by yesdavid** [comment]
I agree, @joeroe!
